### ISSUE TITLE
Changed name to pune

### ISSUE THREAD

**Issue by finnp** [nodeschool/pune#1]
Hey @adroittech,

just wanted to let you know that I changed the name of the repo to `pune`. That's more descriptive and also important for the nodeschoo.io chapters page.

If you create a `gh-pages` branch on this repository, you will get a url `nodeschool.io/<reponame>`, so in your case now `nodeschool.io/pune`.

Also there is already a Delhi chapter, so having this called India would be a bit confusing :)

Best,
Finn

**Comment by adroittech** [comment]
Hey,
Sounds good to me.
Cheers,
Nirav
